////

|metadata|
{
    "name": "custom-properties-datapresenterbase",
    "controlName": [],
    "tags": [],
    "guid": "9e23f412-4e82-42b6-b622-b0a507877206",  
    "buildFlags": [],
    "createdOn": "2014-04-30T19:25:59.0687065Z"
}
|metadata|
////

= Custom Properties - DataPresenterBase

== _DataPresenterBase_   Custom Properties Reference

=== Introduction

This topic provides reference information about the  _DataPresenterBase_   custom properties for  _xamDataGrid_™,  _xamDataPresenter_™,  _xamDataCards_™, and  _xamDataCarousel_™ controls. Use the control property access method’s custom properties for extending the type of objects referenced below (See link:accessing-controls-properties.html[Accessing Controls' Properties] for more details).

=== Custom properties reference chart

The following table summarizes the custom properties for DataPresenterBase.

[options="header", cols="a,a,a"]
|====
|Custom property|Applied Object Type|Returns...

| _CellValuePresenter_ 
|`Infragistics.Windows.DataPresenter.Cell`
|Returns the CellValuePresenter object for the Cell.

|====