////

|metadata|
{
    "name": "whats-new-in-2012-volume-2",
    "controlName": [],
    "tags": [],
    "guid": "edc67ca9-1637-431a-8fa1-73cc0f4c9c73",  
    "buildFlags": [],
    "createdOn": "2012-10-29T22:51:53.1055899Z"
}
|metadata|
////

= What's New in 2012 Volume 2

== Topic Overview

=== In this topic

This topic contains the following sections:

* <<_Ref315857201,What’s New in 2012 Volume 2>>
* <<_Ref315857301,Breaking Changes in 2012 Volume 2>>

[[_Ref315857201]]
== What’s New in 2012 Volume 2

=== Features Overview

The following table summarizes the new features of the  _{ProductName}_   2012 Volume 2. Additional details are available following the summary table.

[options="header", cols="a,a,a"]
|====
|Control|Feature|Description

|<<_Ref339233904,OlapViewModel Controls>>
|<<_Ref339234022,OlapViewModel control proxy>>
|Introduces action methods that allow runtime data manipulation of OlapViewModel’s supported controls.

| link:subitems-recording.html[Recording of Subitems in WPF Controls]
|Supports recording of Subitems in: 

* link:subitems-recording.html#_Ref338010188[xamDataGrid] 

* link:subitems-recording.html#_Ref338010197[xamDataTree] 

* link:subitems-recording.html#_Ref338010200[xamDockManager] 

* link:subitems-recording.html#_Ref338010214[xamGrid] 

* link:subitems-recording.html#_Ref338010222[xamMenu] 

* link:subitems-recording.html#_Ref338010244[xamContextMenu] 

* link:subitems-recording.html#_Ref338010250[xamNetworkNode] 

* link:subitems-recording.html#_Ref338010255[xamOutlookBar] 

* link:subitems-recording.html#_Ref338010260[xamPivotDataSelector] 

* link:subitems-recording.html#_Ref338010263[xamPivotGrid] 

* link:subitems-recording.html#_Ref338010272[xamRibbon] 

* link:subitems-recording.html#_Ref338010275[xamTabControl] 

* link:subitems-recording.html#_Ref338010281[xamTreemap] 

|Provides support for recording mouse actions, on subitems, for a list of supported controls.

|<<_Ref338008711,xamDataChart>>
|<<_Ref338009940,Property Changes>>
|Introduces changes in the _xamDataChart_ control’s properties and methods.

|<<_Ref339874137,xamGantt>>
|<<_Ref339874216,xamGantt control proxy>>
|Introduces support for the _xamGantt_ control’s properties and methods.

|<<_Ref339874189,xamNetworkNode>>
|<<_Ref339874226,Changes in xamNetworkNode control proxy>>
|Introduces changes in the _xamNetworkNode_ control’s properties and methods.

|<<_Ref338008722,xamPivotGrid>>
|<<_Ref338009959,Improvements in xamPivotGrid control proxy>>
|Introduces improvements in the _xamPivotGrid_ control’s proxy.

|
|<<_Ref339874246,SetCellData method>>
|Sets the cell value property to the supplied value.

|
|<<_Ref339874255,GetCellData method>>
|Returns the value property of the supplied column.

|<<_Ref339874204,xamSyntaxEditor>>
|<<_Ref339874265,xamSyntaxEditor control proxy>>
|Introduces support for the _XamSyntaxEditor_ control properties and methods.

|====

[[_Ref339233904]]
== _OlapViewModel_   Controls

[[_Ref339234022]]

=== OlapViewModel control proxy

The release of 2012 volume 2 adds link:{ApiPlatform}test.controls.grids.xampivotgrid~infragisticswpf.test.controls.grids.olapviewmodelproxy.html[OlapViewModelProxy] for the controls that use OlapViewModel such as  _xamPivotGrid_   and  _xamPivotDataSelector_  , with the release of 2012 volume 2. This proxy contains user recordable actions with the ability to replay, via script or User Interface (UI) for testing, the featured areas, and inspecting and manipulating runtime data while recording the actions such as moving, removing and filtering items of the  _XamPivotDataSelector_   and  _XamPivotGrid_   controls.

==== Related Links

* link:olapviewmodel-manipulating-data-at-runtime.html[OlapViewModel - Manipulating Data at Runtime]

[[_Ref338008741]]

[[_Ref338008711]]
== _xamDataChart_

[[_Ref338009940]]

=== Property Changes

The changes introduced by  _xamDataChart_   control include  _TableVerify,_    _DataPoints_   properties and  _GetDataPointCount_   method, which now support  _StackedSeriesBase_   and  _HighDensityScatterSeries_   data series objects.

If the  _xamDataChart_   contains 2 series objects, of which the second one is a  _StackedBarSeries_  , then the  _StackedBarSeries_   sub series will have indices 1.1, 1.2, and so on.

Consider the following examples that use the  _GetDataPointCount_   method, which returns the data points’ count for each of the StackedSeries’ sub series.

1. Returning the data points’ count of the first series.

[source,csharp]
----
msgbox WpfWindow("WindowID").XamDataChart("ChartID").GetDataPointCount(0)
----

2. Returning the data points’ count of the second series. Since the second series is a StackedBarSeries, it returns the sum of the data points’ count of all sub series within the StackedBarSeries.

[source,csharp]
----
msgbox WpfWindow("WindowID").XamDataChart("ChartID").GetDataPointCount(1)
----

3. Returning the data points’ count of the first series as 0.0 equals 0.

[source,csharp]
----
msgbox WpfWindow("WindowID").XamDataChart("ChartID").GetDataPointCount(0.0)
----

4. Returning the data points’ count of the first sub series of the StackedBarSeries.

[source,csharp]
----
msgbox WpfWindow("WindowID").XamDataChart("ChartID").GetDataPointCount(1.1)
----

5. Returning the data points’ count of the second sub series of the StackedBarSeries.

[source,csharp]
----
msgbox WpfWindow("WindowID").XamDataChart("ChartID").GetDataPointCount(1.2)
----

.Note:
[NOTE]
====
Since -0 equals 0, indices of -0, -0.1,-0.2 and so on equate to their absolute values (|-0|, |-0.1| and |-0.2|). All other negative indices such as -1, -1.1,-2 and so on throw an, “index out of range exception.”
====

.Note
[NOTE]
====
If a series does not exist, the default return value is -1.
====

[[_Ref339874137]]
== _xamGantt_

[[_Ref339874216]]

=== xamGantt control proxy

The release of 2012 volume 2 adds support to the  _xamGantt_   control. This proxy contains user recordable actions with the ability to replay, via either script or User Interface (UI), to test and inspect the control’s featured areas of the xamGantt.

==== Related Links

* link:xamgantt.html[xamGantt]

[[_Ref339874189]]
== _xamNetworkNode_

[[_Ref339874226]]

=== Changes in xamNetworkNode control proxy

Enhancements to the link:{ApiPlatform}test.networknode~infragisticswpf.test.networknode.xamnetworknodeproxy.html[XamNetworkNodeProxy] include more user recordable actions and the ability to replay, via script or User Interface (UI), for testing and inspecting various control items and areas.

==== Related Links

* link:xamnetworknode.html[xamNetworkNode]

[[_Ref338008722]]
== _xamPivotGrid_

[[_Ref338009959]]

=== Improvements in xamPivotGrid control proxy

Included improvements to the link:{ApiPlatform}test.controls.grids.xampivotgrid~infragisticswpf.test.controls.grids.xampivotgridproxy.html[XamPivotGridProxy] are the reintroduction of features that previously existed in earlier versions of Infragistics  _xamPivotGrid_   control.

Recording operation

* Records actions by triggering the `CellEdited` events on a control inside of a cell matching the column Type with the corresponding column of the cell

Replaying operation

* The replay action first validates `oCellArg` argument, then activates the cell by putting it in edit mode, and finally sets the editor’s text field to the value of `oValue` parameter, prior to exiting the edit mode

[[_Ref339874246]]

=== SetCellData method

The following example demonstrates, with a script, how to use the `SetCellData` method to set a cell’s value in the third data row of the second data column to a value of 4.

[source,csharp]
----
XamPivotGrid("xamPivotGrid1").SetCellData ARRAY(2,1), 4
----

[[_Ref339874255]]

=== GetCellData method

The following example demonstrates, with a script, how to use the `GetCellData` to retrieve the value from a cell in the third data row of the second data column, and displaying it to the screen with a message box:

[source,csharp]
----
msgbox WpfWindow("Test Automation Samples").XamPivotGrid("xamPivotGrid1").GetCellData (ARRAY(2, 1) )
----

[[_Ref339874204]]
== _xamSyntaxEditor_

[[_Ref339874265]]

=== xamSyntaxEditor control proxy

The release of 2012 volume 2 adds support to the  _xamSyntaxEditor_   control. This proxy contains user recordable actions, with the ability to replay, via either script or User Interface (UI), to test and inspect the control’s featured areas of the syntax editor.

==== Related Links

* link:xamsyntaxeditor.html[xamSyntaxEditor]

[[_Ref315857301]]
== Breaking Changes in 2012 Volume 2

=== Overview

The names for some of the Infragistics controls` subitems have changed in 2012 volume 2. The following table lists the controls with their former subitem names along with their corresponding new names.

.Note:
[NOTE]
====
Recording and Replaying use the new subitems, by default. However, you are allowed to use the string equivalents of the old names for reference.
====

==== Example:

For XamRibbon, to replay a `ClickSubItem` method on a RibbonGroup with a header named “Text Style” under tab “Format,” you can use either of the following two Quick Time Profssional™ (QTP) methods:

_1_  _._  `XamRibbon("myRibbon").ClickSubItem rbnGroup, ARRAY("RibbonGroup", "Format", "Text Style"), igAt, 1,2`

_2_  _._  `XamRibbon("myRibbon").ClickSubItem “RibbonGroup”, ARRAY("RibbonGroup", "Format", "Text Style"), igAt, 1,2`

[options="header", cols="a,a,a"]
|====
|Controls|Former subitem name|New subitem name

.8| _XamRibbon_ 
|`RibbonGroup`
|`rbnGroup`

|`RibbonTool`
|`rbnTool`

|`ApplicationMenuLeftArea`
|`rbnAppMenuLeft`

|`ApplicationMenuRecentItems`
|`rbnAppMenuRecent`

|`ApplicationMenuFooterToolbar`
|`rbnAppMenuFooter`

|`QuickAccessToolbar`
|`rbnQAT`

|`QuickCustomizeMenuPanel`
|`rbnQuickCustMenu`

|`RibbonTabItem`
|`rbnTabItem`

| _XamMenu_ 
.2|`MenuItem`
.2|`menuItem`

| _XamContextMenu_ 

.4| _XamOutlookBar_ 
|`OutlookBarGroup`
|`obarGroup`

|`SelectedGroupHeader`
|`obarGroupHeader`

|`SelectedGroupContent`
|`obarGroupContent`

|`OverflowArea`
|`obarOverflowArea`

| _XamTreeMap_ 
|`TreemapNode`
|`tmapNode`

.3| _XamDockManager_ 
|`PaneContent`
|`dockPaneContent`

|`PaneTab`
|`dockPaneTab`

|`PaneHeader`
|`dockPaneHeader`

|====